
addons:
  apt:
    packages:
    - aria2
    #- gnupg
    - gnupg2
    - graphviz
    - openssl
before_install:
- aria2c --file-allocation=none -c -x 10 -s 10 -m 0 --console-log-level=notice --log-level=notice --summary-interval=0 -o apache-maven-3.5.3-bin.zip https://archive.apache.org/dist/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.zip && unzip -qq apache-maven-3.5.3-bin.zip
- export M2_HOME=$PWD/apache-maven-3.5.3
- export PATH=$M2_HOME/bin:$PATH
branches:
  only:
  #- master # do nothing on master branch
  - develop # snapshots on develop branch
  - /^feature\/.*$/ # build and test on feature branches
  - /^hotfix\/.*$/ # release on hotfix branches
  - /^release\/.*$/ # release on release branches
  #- /^v\d+\.\d+(\.\d+)?(-\S*)?/ # build and publish a github release (can skip tests here) or do nothing on version tags
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.gradle"
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"

dist: trusty
env:
  global:
  # i.e. CI_OPT_CI_SCRIPT=https://github.com/ci-and-cd/maven-build/raw/master/src/main/ci-script/lib_ci.sh
  - CI_OPT_CI_SCRIPT=https://github.com/ci-and-cd/maven-build/raw/master/src/main/ci-script/lib_ci.sh
  - CI_OPT_INFRASTRUCTURE=opensource
  - MAVEN_SKIP_RC=true
group: edge
install: true
jdk:
- oraclejdk8
#- oraclejdk9
language: java
script:
# When prefixed with `travis_wait 30`, no log output until it is done.
# see: https://github.com/travis-ci/travis-ci/issues/4190 or https://github.com/HaxeFoundation/hxcpp/issues/709
- while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
- bash ci.sh mvn clean install sonar:sonar site deploy site-deploy
- kill %1
services:
- docker
sudo: required
