
version: '2.1'
services:
  config-server-develop:
    extends:
      file: docker-compose-base.yml
      service: base-config-server
    container_name: ${INSTANCE_NAME:-config-server}.${INSTANCE_DOMAIN:-local}
    environment:
    - AUTH_CONFIG_SEARCHPATHS=${AUTH_CONFIG_SEARCHPATHS:-auth-label-{label},auth-profile-{profile}}

    - EUREKA_INSTANCE_NONSECUREPORT=${EUREKA_INSTANCE_NONSECUREPORT:-8888}
    - SERVER_PORT=${SERVER_PORT:-8888}

    hostname: ${INSTANCE_NAME:-config-server}.${INSTANCE_DOMAIN:-local}
    networks:
      local-network:
        ipv4_address: 172.16.238.18
        ipv6_address: 2001:3984:3989::18
    ports:
    - "${EUREKA_INSTANCE_NONSECUREPORT:-8888}:${SERVER_PORT:-8888}"
    volumes:
    - data:/tmp
    - data:/root/.data

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      - subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
